// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPsQajK_HDL44tIrvQbXT3UFrk62_eLKI',
    appId: '1:578743923308:web:455246b73856e903e4de49',
    messagingSenderId: '578743923308',
    projectId: 'livestockapp-50d71',
    authDomain: 'livestockapp-50d71.firebaseapp.com',
    storageBucket: 'livestockapp-50d71.firebasestorage.app',
    measurementId: 'G-E7TB26QTZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtHkPqKGGqUMVpkSky-Eh8u9Z6PlSJJ34',
    appId: '1:578743923308:android:f98bacb86071d2dee4de49',
    messagingSenderId: '578743923308',
    projectId: 'livestockapp-50d71',
    storageBucket: 'livestockapp-50d71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdD8WmJjP6Bpg7IIC9mOPOXtK68KfcXvc',
    appId: '1:578743923308:ios:f6ba2ff33a3db625e4de49',
    messagingSenderId: '578743923308',
    projectId: 'livestockapp-50d71',
    storageBucket: 'livestockapp-50d71.firebasestorage.app',
    iosBundleId: 'com.example.capstoneproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdD8WmJjP6Bpg7IIC9mOPOXtK68KfcXvc',
    appId: '1:578743923308:ios:f6ba2ff33a3db625e4de49',
    messagingSenderId: '578743923308',
    projectId: 'livestockapp-50d71',
    storageBucket: 'livestockapp-50d71.firebasestorage.app',
    iosBundleId: 'com.example.capstoneproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPsQajK_HDL44tIrvQbXT3UFrk62_eLKI',
    appId: '1:578743923308:web:105fb9fc9acef66de4de49',
    messagingSenderId: '578743923308',
    projectId: 'livestockapp-50d71',
    authDomain: 'livestockapp-50d71.firebaseapp.com',
    storageBucket: 'livestockapp-50d71.firebasestorage.app',
    measurementId: 'G-0LN8DRYFJC',
  );
}
